import { Announcement } from './announcement';
export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: 301,
    title: 'Announcement 1',
    postedFrom: 'Class 1',
    detail: "Hello WOrld! This is an announcment!!!",
    shortDetail: "Hello World Hello World ",
    postedBy: "Peter",
    postedAt: "Today",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 302,
    title: 'Announcement 2',
    postedFrom: 'Class 5',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "Linda",
    postedAt: "Today",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 303,
    title: 'Announcement 3',
    postedFrom: 'Office 1',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "Marry",
    postedAt: "Dec 19, 2016",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 304,
    title: 'Announcement 4',
    postedFrom: 'Club 1',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "John",
    postedAt: "Nov 10, 2016",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 305,
    title: 'Announcement 5',
    postedFrom: 'Club 3',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "Peter",
    postedAt: "Aug 8, 2016",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 306,
    title: 'Announcement 6',
    postedFrom: 'Class 1',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "Peter",
    postedAt: "Today",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 307,
    title: 'Announcement 7',
    postedFrom: 'Class 5',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "Linda",
    postedAt: "Today",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 308,
    title: 'Announcement 8',
    postedFrom: 'Office 1',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "Marry",
    postedAt: "Dec 19, 2016",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 309,
    title: 'Announcement 9',
    postedFrom: 'Club 1',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "John",
    postedAt: "Nov 10, 2016",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 310,
    title: 'Announcement 10',
    postedFrom: 'Club 3',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "Peter",
    postedAt: "Aug 8, 2016",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 311,
    title: 'Announcement 11',
    postedFrom: 'Class 1',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "Peter",
    postedAt: "Today",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 312,
    title: 'Announcement 12',
    postedFrom: 'Class 5',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "Linda",
    postedAt: "Today",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 313,
    title: 'Announcement 13',
    postedFrom: 'Office 1',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "Marry",
    postedAt: "Dec 19, 2016",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 314,
    title: 'Announcement 14',
    postedFrom: 'Club 1',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "John",
    postedAt: "Nov 10, 2016",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  },
  {
    id: 315,
    title: 'Announcement 15',
    postedFrom: 'Club 3',
    detail: "Hello World Hello World ",
    shortDetail: "Hello World Hello World ",
    postedBy: "Peter",
    postedAt: "Aug 8, 2016",
    isNew: false,
    hasNotified: false,
    priority: "1",
    sticky: "N"
  }
]
