import { Bookmark } from './bookmark';

export const ALLBOOKMARKS: Bookmark[] = [{
  "iconCode": "C",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729019/workstation-336369_640.jpg?fileId=64046192",
  "subject": "Course Catalog",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76382&cx=22.55",
  "iconBg": "#363636",
  "isMyFavour": false,
  "isRecent": true,
  "id": 729019,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Course Catalog",
  "seq": 1,
  "iconType": 102
},
{
  "iconCode": "B",
  "subject": "Academic Calendar",
  "link": "https://ccstage.campuscruiser.com/q?pg=home_calendar&tg=Calendar-monthly&cmd=load&dt=20170301&cx=22.55",
  "iconBg": "#A63379",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729020,
  "iconFg": "#FFF",
  "description": "Academic Calendar",
  "isPopular": true,
  "seq": 2,
  "iconType": 101,
  "imgIcon": "",
}, {
  "iconCode": "P",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729021/parking.jpg?fileId=64046171",
  "subject": "Parking Services",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76383&cx=22.55",
  "iconBg": "#FF2C00",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729021,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Parking Services",
  "seq": 3,
  "iconType": 102
}, {
  "iconCode": "H",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729022/219H.jpg?fileId=64046158",
  "subject": "Housing",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76384&cx=22.55",
  "iconBg": "#FF7A00",
  "isMyFavour": false,
  "isRecent": true,
  "id": 729022,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Housing",
  "seq": 4,
  "iconType": 102
}, {
  "iconCode": "S",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729023/mathematics-1622448_640.jpg?fileId=64046157",
  "subject": "Student Advising",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76385&cx=22.55",
  "iconBg": "#58ACEC",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729023,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Student Advising",
  "seq": 5,
  "iconType": 102
}, {
  "iconCode": "L",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729024/book-2073023_640.jpg?fileId=64046190",
  "subject": "Library",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76386&cx=22.55",
  "iconBg": "#363636",
  "isMyFavour": false,
  "isRecent": true,
  "id": 729024,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Library",
  "seq": 6,
  "iconType": 102
}, {
  "iconCode": "G",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729025/index.jpg?fileId=64046160",
  "subject": "Gmail",
  "link": "https://mail.google.com/mail/u/0/#inbox",
  "iconBg": "#FEFEFE",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729025,
  "iconFg": "#333",
  "isPopular": true,
  "description": "Gmail",
  "seq": 7,
  "iconType": 102
}, {
  "iconCode": "T",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729026/globe-967304_640.jpg?fileId=64046154",
  "subject": "Transfer Students",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76387&cx=22.55",
  "iconBg": "#FF2C00",
  "isMyFavour": false,
  "isRecent": true,
  "id": 729026,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Transfer Students",
  "seq": 8,
  "iconType": 102
}, {
  "isRecent": true,
  "iconCode": "D",
  "id": 729027,
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729027/dining.jpg?fileId=64046173",
  "isPopular": true,
  "description": "Dining & Meal Plans",
  "subject": "Dining & Meal Plans",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76388&cx=22.55",
  "seq": 9,
  "isMyFavour": false,
  "iconType": 102,
  "iconFg": "#FFF",
  "iconBg": "#21C518"
}, {
  "iconCode": "I",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729028/student-id-1863434_640.jpg?fileId=64046187",
  "subject": "ID Card",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76390&cx=22.55",
  "iconBg": "#21C518",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729028,
  "iconFg": "#FFF",
  "isPopular": false,
  "description": "ID Card",
  "seq": 10,
  "iconType": 102
}]




export const POPULARBOOKMARKS: Bookmark[] = [{
  "iconCode": "C",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729019/workstation-336369_640.jpg?fileId=64046192",
  "subject": "Course Catalog",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76382&cx=22.55",
  "iconBg": "#363636",
  "isMyFavour": false,
  "isRecent": true,
  "id": 729019,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Course Catalog",
  "seq": 6,
  "iconType": 102
},
{
  "iconCode": "B",
  "subject": "Academic Calendar",
  "link": "https://ccstage.campuscruiser.com/q?pg=home_calendar&tg=Calendar-monthly&cmd=load&dt=20170301&cx=22.55",
  "iconBg": "#A63379",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729020,
  "iconFg": "#FFF",
  "description": "Academic Calendar",
  "isPopular": true,
  "seq": 5,
  "iconType": 101,
  "imgIcon": "",
}, {
  "iconCode": "P",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729021/parking.jpg?fileId=64046171",
  "subject": "Parking Services",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76383&cx=22.55",
  "iconBg": "#FF2C00",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729021,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Parking Services",
  "seq": 3,
  "iconType": 102
}, {
  "iconCode": "H",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729022/219H.jpg?fileId=64046158",
  "subject": "Housing",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76384&cx=22.55",
  "iconBg": "#FF7A00",
  "isMyFavour": false,
  "isRecent": true,
  "id": 729022,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Housing",
  "seq": 4,
  "iconType": 102
}, {
  "iconCode": "S",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729023/mathematics-1622448_640.jpg?fileId=64046157",
  "subject": "Student Advising",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76385&cx=22.55",
  "iconBg": "#58ACEC",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729023,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Student Advising",
  "seq": 2,
  "iconType": 102
}, {
  "iconCode": "L",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729024/book-2073023_640.jpg?fileId=64046190",
  "subject": "Library",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76386&cx=22.55",
  "iconBg": "#363636",
  "isMyFavour": false,
  "isRecent": true,
  "id": 729024,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Library",
  "seq": 1,
  "iconType": 102
}, {
  "iconCode": "G",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729025/index.jpg?fileId=64046160",
  "subject": "Gmail",
  "link": "https://mail.google.com/mail/u/0/#inbox",
  "iconBg": "#FEFEFE",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729025,
  "iconFg": "#333",
  "isPopular": true,
  "description": "Gmail",
  "seq": 9,
  "iconType": 102
}, {
  "iconCode": "T",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729026/globe-967304_640.jpg?fileId=64046154",
  "subject": "Transfer Students",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76387&cx=22.55",
  "iconBg": "#FF2C00",
  "isMyFavour": false,
  "isRecent": true,
  "id": 729026,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Transfer Students",
  "seq": 7,
  "iconType": 102
}, {
  "isRecent": true,
  "iconCode": "D",
  "id": 729027,
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729027/dining.jpg?fileId=64046173",
  "isPopular": true,
  "description": "Dining & Meal Plans",
  "subject": "Dining & Meal Plans",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76388&cx=22.55",
  "seq": 8,
  "isMyFavour": false,
  "iconType": 102,
  "iconFg": "#FFF",
  "iconBg": "#21C518"
}]

export const RECENTBOOKMARKS: Bookmark[] = [{
  "iconCode": "C",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729019/workstation-336369_640.jpg?fileId=64046192",
  "subject": "Course Catalog",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76382&cx=22.55",
  "iconBg": "#363636",
  "isMyFavour": false,
  "isRecent": true,
  "id": 729019,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Course Catalog",
  "seq": 7,
  "iconType": 102
},
{
  "iconCode": "B",
  "subject": "Academic Calendar",
  "link": "https://ccstage.campuscruiser.com/q?pg=home_calendar&tg=Calendar-monthly&cmd=load&dt=20170301&cx=22.55",
  "iconBg": "#A63379",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729020,
  "iconFg": "#FFF",
  "description": "Academic Calendar",
  "isPopular": true,
  "seq": 8,
  "iconType": 101,
  "imgIcon": "",
}, {
  "iconCode": "P",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729021/parking.jpg?fileId=64046171",
  "subject": "Parking Services",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76383&cx=22.55",
  "iconBg": "#FF2C00",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729021,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Parking Services",
  "seq": 1,
  "iconType": 102
}, {
  "iconCode": "H",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729022/219H.jpg?fileId=64046158",
  "subject": "Housing",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76384&cx=22.55",
  "iconBg": "#FF7A00",
  "isMyFavour": false,
  "isRecent": true,
  "id": 729022,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Housing",
  "seq": 3,
  "iconType": 102
}, {
  "iconCode": "S",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729023/mathematics-1622448_640.jpg?fileId=64046157",
  "subject": "Student Advising",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76385&cx=22.55",
  "iconBg": "#58ACEC",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729023,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Student Advising",
  "seq": 2,
  "iconType": 102
}, {
  "iconCode": "L",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729024/book-2073023_640.jpg?fileId=64046190",
  "subject": "Library",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76386&cx=22.55",
  "iconBg": "#363636",
  "isMyFavour": false,
  "isRecent": true,
  "id": 729024,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Library",
  "seq": 4,
  "iconType": 102
}, {
  "iconCode": "G",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729025/index.jpg?fileId=64046160",
  "subject": "Gmail",
  "link": "https://mail.google.com/mail/u/0/#inbox",
  "iconBg": "#FEFEFE",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729025,
  "iconFg": "#333",
  "isPopular": true,
  "description": "Gmail",
  "seq": 10,
  "iconType": 102
}, {
  "iconCode": "T",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729026/globe-967304_640.jpg?fileId=64046154",
  "subject": "Transfer Students",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76387&cx=22.55",
  "iconBg": "#FF2C00",
  "isMyFavour": false,
  "isRecent": true,
  "id": 729026,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Transfer Students",
  "seq": 6,
  "iconType": 102
}, {
  "isRecent": true,
  "iconCode": "D",
  "id": 729027,
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729027/dining.jpg?fileId=64046173",
  "isPopular": true,
  "description": "Dining & Meal Plans",
  "subject": "Dining & Meal Plans",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76388&cx=22.55",
  "seq": 9,
  "isMyFavour": false,
  "iconType": 102,
  "iconFg": "#FFF",
  "iconBg": "#21C518"
}, {
  "iconCode": "I",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729028/student-id-1863434_640.jpg?fileId=64046187",
  "subject": "ID Card",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76390&cx=22.55",
  "iconBg": "#21C518",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729028,
  "iconFg": "#FFF",
  "isPopular": false,
  "description": "ID Card",
  "seq": 5,
  "iconType": 102
}]



export const MYFAVBOOKMARKS: Bookmark[] = [
{
  "iconCode": "B",
  "subject": "Academic Calendar",
  "link": "https://ccstage.campuscruiser.com/q?pg=home_calendar&tg=Calendar-monthly&cmd=load&dt=20170301&cx=22.55",
  "iconBg": "#A63379",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729020,
  "iconFg": "#FFF",
  "description": "Academic Calendar",
  "isPopular": true,
  "seq": 3,
  "iconType": 101,
  "imgIcon": "",
}, {
  "iconCode": "P",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729021/parking.jpg?fileId=64046171",
  "subject": "Parking Services",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76383&cx=22.55",
  "iconBg": "#FF2C00",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729021,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Parking Services",
  "seq": 4,
  "iconType": 102
}, {
  "iconCode": "S",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729023/mathematics-1622448_640.jpg?fileId=64046157",
  "subject": "Student Advising",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76385&cx=22.55",
  "iconBg": "#58ACEC",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729023,
  "iconFg": "#FFF",
  "isPopular": true,
  "description": "Student Advising",
  "seq": 1,
  "iconType": 102
}, {
  "iconCode": "G",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729025/index.jpg?fileId=64046160",
  "subject": "Gmail",
  "link": "https://mail.google.com/mail/u/0/#inbox",
  "iconBg": "#FEFEFE",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729025,
  "iconFg": "#333",
  "isPopular": true,
  "description": "Gmail",
  "seq": 2,
  "iconType": 102
}, {
  "iconCode": "I",
  "imgIcon": "https://ccstage.campuscruiser.com/files/manage/4/22.55/__bookmark/729028/student-id-1863434_640.jpg?fileId=64046187",
  "subject": "ID Card",
  "link": "https://ccstage.campuscruiser.com/PageServlet?pg=webpageProxy&tg=WebPage-proxy&from=22.55&page=76390&cx=22.55",
  "iconBg": "#21C518",
  "isMyFavour": true,
  "isRecent": true,
  "id": 729028,
  "iconFg": "#FFF",
  "isPopular": false,
  "description": "ID Card",
  "seq": 5,
  "iconType": 102
}]