import { Bookmark } from './bookmark';

export const BOOKMARKS: Bookmark[] = [
  {id: 201, subject: 'Baidu 1', description: 'Baidu', link: "http://www.163.com", imgIcon:"assets/images/bookmarks/1.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: true, isPopular: false, seq: 1},
  {id: 202, subject: 'Baidu 2', description: 'Baidu', link: "http://www.sina.com", imgIcon:"assets/images/bookmarks/2.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: false, isPopular: true, seq: 2},
  {id: 203, subject: 'Baidu 3', description: 'Baidu', link: "http://www.sohu.com", imgIcon:"assets/images/bookmarks/3.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: true, isPopular: false, seq: 3},
  {id: 204, subject: 'Baidu 4', description: 'Baidu', link: "http://www.360.com", imgIcon:"assets/images/bookmarks/4.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: false, isPopular: true, seq: 4},
  {id: 205, subject: 'Baidu 5', description: 'Baidu', link: "http://www.jd.com", imgIcon:"assets/images/bookmarks/5.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: true, isPopular: false, seq: 5},
  {id: 206, subject: 'Baidu 6', description: 'Baidu', link: "http://www.baidu.com", imgIcon:"assets/images/bookmarks/6.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: false, isPopular: true, seq: 6},
  {id: 207, subject: 'Baidu 7', description: 'Baidu', link: "http://www.jd.com", imgIcon:"assets/images/bookmarks/7.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: true, isRecent: true, isPopular: false, seq: 7},
  {id: 208, subject: 'Baidu 8', description: 'Baidu', link: "http://www.163.com", imgIcon:"assets/images/bookmarks/8.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: true, isRecent: false, isPopular: true, seq: 8},
  {id: 209, subject: 'Baidu 9', description: 'Baidu', link: "http://www.baidu.com", imgIcon:"assets/images/bookmarks/9.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: true, isRecent: true, isPopular: false, seq: 9},
  {id: 210, subject: 'Baidu 10', description: 'Baidu', link: "http://www.amazon.com", imgIcon:"assets/images/bookmarks/10.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: false, isPopular: true, seq: 10},
  {id: 211, subject: 'Baidu 11', description: 'Baidu', link: "http://www.sina.com", imgIcon:"assets/images/bookmarks/11.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: true, isPopular: false, seq: 11},
  {id: 212, subject: 'Baidu 12', description: 'Baidu', link: "http://www.baidu.com", imgIcon:"assets/images/bookmarks/12.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: false, isPopular: true, seq: 12},
  {id: 213, subject: 'Baidu 13', description: 'Baidu', link: "http://www.baidu.com", imgIcon:"assets/images/bookmarks/13.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: true, isPopular: false, seq: 13},
  {id: 214, subject: 'Baidu 14', description: 'Baidu', link: "http://www.baidu.com", imgIcon:"assets/images/bookmarks/14.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: true, isRecent: false, isPopular: true, seq: 14},
  {id: 215, subject: 'Baidu 15', description: 'Baidu', link: "http://www.baidu.com", imgIcon:"assets/images/bookmarks/15.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: true, isRecent: true, isPopular: false, seq: 15},
  {id: 216, subject: 'Baidu 16', description: 'Baidu', link: "http://www.sohu.com", imgIcon:"assets/images/bookmarks/16.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: false, isPopular: true, seq: 16},
  {id: 217, subject: 'Baidu 17', description: 'Baidu', link: "http://www.baidu.com", imgIcon:"assets/images/bookmarks/17.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: true, isPopular: false, seq: 17},
  {id: 218, subject: 'Baidu 18', description: 'Baidu', link: "http://www.jd.com", imgIcon:"assets/images/bookmarks/18.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: false, isPopular: true, seq: 18},
  {id: 219, subject: 'Baidu 19', description: 'Baidu', link: "http://www.baidu.com", imgIcon:"assets/images/bookmarks/19.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: true, isRecent: true, isPopular: false, seq: 19},
  {id: 220, subject: 'Baidu 20', description: 'Baidu', link: "http://www.amazon.com", imgIcon:"assets/images/bookmarks/20.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: false, isRecent: false, isPopular: true, seq: 20},
  {id: 221, subject: 'Baidu 21', description: 'Baidu', link: "http://www.baidu.com", imgIcon:"assets/images/bookmarks/21.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: true, isRecent: true, isPopular: false, seq: 21},
  {id: 222, subject: 'Baidu 22', description: 'Baidu', link: "http://www.baidu.com", imgIcon:"assets/images/bookmarks/22.jpg", iconType:102, iconCode: "B", iconBg: "44a6ff", iconFg: "#000", isMyFavour: true, isRecent: false, isPopular: true, seq: 22}

]  
  