import { Event } from './event';

export const EVENTS: Event[] = [
  { id: 511, calendar: "Athletics Schedule", title: "NCAA Div III Championships (Men's + Women's Swimming)", postedBy: "Anthony Ma", detail: null, location: null, startDate: new Date(2017, 3, 15), endDate: new Date(2017, 3, 15), startTime: 11, endTime: 20, allDay: false, start: null, end: null, repeatInfo: "This event repeats every day until 03/18/2017. " },
  { id: 512, calendar: "Athletics Schedule", title: "NCAA Div III Championships (Men's + Women's Swimming)", postedBy: "Anthony Ma", detail: null, location: null, startDate: new Date(2017, 3, 16), endDate: new Date(2017, 3, 16), startTime: 11, endTime: 20, allDay: false, start: null, end: null, repeatInfo: "This event repeats every day until 03/18/2017. " },
  { id: 513, calendar: "Athletics Schedule", title: "NCAA Div III Championships (Men's + Women's Swimming)", postedBy: "Anthony Ma", detail: null, location: null, startDate: new Date(2017, 3, 17), endDate: new Date(2017, 3, 17), startTime: 11, endTime: 20, allDay: false, start: null, end: null, repeatInfo: "This event repeats every day until 03/18/2017. " },
  { id: 514, calendar: "Athletics Schedule", title: "NCAA Div III Championships (Men's + Women's Swimming)", postedBy: "Anthony Ma", detail: null, location: null, startDate: new Date(2017, 3, 18), endDate: new Date(2017, 3, 18), startTime: 11, endTime: 20, allDay: false, start: null, end: null, repeatInfo: "This event repeats every day until 03/18/2017. " },
  { id: 515, calendar: "Master Campus", title: "Last day to submit Change of Major Form for Fall Class Registration", postedBy: "Anthony Ma", detail: null, location: null, startDate: new Date(2017, 3, 20), endDate: new Date(2017, 3, 20), startTime: 8, endTime: 9, allDay: false, start: null, end: null, repeatInfo: null },
  { id: 516, calendar: "Athletics Schedule", title: "Men's Basketball VS St. Peter's", postedBy: "Anthony Ma", detail: null, location: "Plainfield Gym", startDate: new Date(2017, 3, 22), endDate: new Date(2017, 3, 22), startTime: 17.5, endTime: 20.5, allDay: false, start: null, end: null, repeatInfo: null },
  { id: 517, calendar: "Athletics Schedule", title: "Women's Fencing VS Newark", postedBy: "Anthony Ma", detail: null, location: "Away", startDate: new Date(2017, 3, 24), endDate: new Date(2017, 3, 24), startTime: 15, endTime: 18, allDay: false, start: null, end: null, repeatInfo: null },
  { id: 518, calendar: "Strata Basic Demo", title: "Residence Halls close at 8:00 PM", postedBy: "Anthony Ma", detail: "Closed for the duration of Spring Break", location: null, startDate: new Date(2017, 3, 26), endDate: new Date(2017, 3, 26), startTime: 20, endTime: 21, allDay: false, start: null, end: null, repeatInfo: null },
  { id: 519, calendar: "Master Campus", title: "Spring Break begins", postedBy: "Anthony Ma", detail: null, location: null, startDate: new Date(2017, 3, 27), endDate: new Date(2017, 3, 27), startTime: 0, endTime: 0, allDay: true, start: null, end: null, repeatInfo: null },
  { id: 520, calendar: "Strata Basic Demo", title: "Spring Mid-Semester Reports sent", postedBy: "Anthony Ma", detail: null, location: null, startDate: new Date(2017, 3, 31), endDate: new Date(2017, 3, 31), startTime: 0, endTime: 0, allDay: true, start: null, end: null, repeatInfo: null },
  { id: 521, calendar: "Strata Basic Demo", title: "Residence Halls re-open", postedBy: "Anthony Ma", detail: "Halls open at 8:00 AM to take in students returning from Spring Break. ", location: null, startDate: new Date(2017, 4, 2), endDate: new Date(2017, 4, 2), startTime: 8, endTime: 20, allDay: false, start: null, end: null, repeatInfo: null },
  { id: 522, calendar: "Strata Basic Demo", title: "Return to classes (Spring Break ends)", postedBy: "Anthony Ma", detail: null, location: null, startDate: new Date(2017, 4, 3), endDate: new Date(2017, 4, 3), startTime: 0, endTime: 0, allDay: true, start: null, end: null, repeatInfo: null },
  { id: 523, calendar: "Master Campus", title: "Fall 2017 Class Registration begins", postedBy: "Anthony Ma", detail: null, location: null, startDate: new Date(2017, 4, 4), endDate: new Date(2017, 4, 4), startTime: 7, endTime: 8, allDay: false, start: null, end: null, repeatInfo: null }

];