import { Event } from './event';

export const EVENTS: Event[] = [
  {id: 511, calendar: "Widener Experience", title: 'Event 1', detail: "Hello World", location: "Room 401", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 9, endTime: 11, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 512, calendar: "Widener Experience", title: 'Event 2', detail: "Hello World", location: "Room 402", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 9, endTime: 10, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 513, calendar: "Middles Experience", title: 'Event 3', detail: "Hello World", location: "Room 403", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 0, endTime: 0, allDay:true, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 514, calendar: "Middles Experience", title: 'Event 4', detail: "Hello World", location: "Room 404", startDate: new Date(2017,2,8), endDate: new Date(2017,2,8), startTime: 9, endTime: 11, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 515, calendar: "Westore Experience", title: 'Event 5', detail: "Hello World", location: "Room 405", startDate: new Date(2017,2,9), endDate: new Date(2017,2,9), startTime: 15, endTime: 21, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 516, calendar: "Westore Experience", title: 'Event 6', detail: "Hello World", location: "Room 406", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 16, endTime: 17, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 517, calendar: "Widener Experience", title: 'Event 7', detail: "Hello World", location: "Room 401", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 9, endTime: 11, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 518, calendar: "Widener Experience", title: 'Event 8', detail: "Hello World", location: "Room 402", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 9, endTime: 10, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 519, calendar: "Middles Experience", title: 'Event 9', detail: "Hello World", location: "Room 403", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 0, endTime: 0, allDay:true, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 520, calendar: "Middles Experience", title: 'Event 10', detail: "Hello World", location: "Room 404", startDate: new Date(2017,2,8), endDate: new Date(2017,2,8), startTime: 9, endTime: 11, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 521, calendar: "Westore Experience", title: 'Event 11', detail: "Hello World", location: "Room 405", startDate: new Date(2017,2,9), endDate: new Date(2017,2,9), startTime: 15, endTime: 21, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 522, calendar: "Westore Experience", title: 'Event 12', detail: "Hello World", location: "Room 406", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 16, endTime: 17, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 523, calendar: "Widener Experience", title: 'Event 13', detail: "Hello World", location: "Room 401", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 9, endTime: 11, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 524, calendar: "Widener Experience", title: 'Event 14', detail: "Hello World", location: "Room 402", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 9, endTime: 10, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 525, calendar: "Middles Experience", title: 'Event 15', detail: "Hello World", location: "Room 403", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 0, endTime: 0, allDay:true, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 526, calendar: "Middles Experience", title: 'Event 16', detail: "Hello World", location: "Room 404", startDate: new Date(2017,2,8), endDate: new Date(2017,2,8), startTime: 9, endTime: 11, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 527, calendar: "Westore Experience", title: 'Event 17', detail: "Hello World", location: "Room 405", startDate: new Date(2017,2,9), endDate: new Date(2017,2,9), startTime: 15, endTime: 21, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 528, calendar: "Westore Experience", title: 'Event 18', detail: "Hello World", location: "Room 406", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 16, endTime: 17, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 529, calendar: "Widener Experience", title: 'Event 19', detail: "Hello World", location: "Room 401", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 9, endTime: 11, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 530, calendar: "Widener Experience", title: 'Event 20', detail: "Hello World", location: "Room 402", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 9, endTime: 10, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 531, calendar: "Middles Experience", title: 'Event 21', detail: "Hello World", location: "Room 403", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 0, endTime: 0, allDay:true, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 532, calendar: "Middles Experience", title: 'Event 22', detail: "Hello World", location: "Room 404", startDate: new Date(2017,2,8), endDate: new Date(2017,2,8), startTime: 9, endTime: 11, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 533, calendar: "Westore Experience", title: 'Event 23', detail: "Hello World", location: "Room 405", startDate: new Date(2017,2,9), endDate: new Date(2017,2,9), startTime: 15, endTime: 21, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null},
  {id: 534, calendar: "Westore Experience", title: 'Event 24', detail: "Hello World", location: "Room 406", startDate: new Date(2017,2,3), endDate: new Date(2017,2,3), startTime: 16, endTime: 17, allDay:false, start:null, end:null, postedBy: "Anthony Ma", repeatInfo: null}


];