import { Event } from './event';

export const EVENTS: Event[] = [
  { id: "511", calendar: "Athletics Schedule", calendarColor: "green", title: "NCAA Div III Championships (Men's + Women's Swimming)", postedBy: "Anthony Ma", detail: null, location: null, start: new Date(2017, 2, 15, 3,15), end: new Date(2017, 2, 15, 3,15), startDate: "", endDate: "", allDay: false, repeatInfo: "This event repeats every day until 03/18/2017. " },
  { id: "512", calendar: "Athletics Schedule", calendarColor: "green", title: "NCAA Div III Championships (Men's + Women's Swimming)", postedBy: "Anthony Ma", detail: null, location: null, start: new Date(2017, 2, 16, 3,15), end: new Date(2017, 2, 16, 3,15), startDate: "", endDate: "", allDay: false, repeatInfo: "This event repeats every day until 03/18/2017. " },
  { id: "513", calendar: "Athletics Schedule", calendarColor: "red", title: "NCAA Div III Championships (Men's + Women's Swimming)", postedBy: "Anthony Ma", detail: null, location: null, start: new Date(2017, 2, 17, 3,15), end: new Date(2017, 2, 17, 3,15), startDate: "", endDate: "", allDay: false, repeatInfo: "This event repeats every day until 03/18/2017. " },
  { id: "514", calendar: "Athletics Schedule", calendarColor: "red", title: "NCAA Div III Championships (Men's + Women's Swimming)", postedBy: "Anthony Ma", detail: null, location: null, start: new Date(2017, 2, 18, 3,15), end: new Date(2017, 2, 18, 3,15), startDate: "", endDate: "", allDay: false, repeatInfo: "This event repeats every day until 03/18/2017. " },
  { id: "515", calendar: "Master Campus", calendarColor: "blue", title: "Last day to submit Change of Major Form for Fall Class Registration", postedBy: "Anthony Ma", detail: null, location: null, start: new Date(2017, 2, 20, 3,15), end: new Date(2017, 2, 20, 3,15), startDate: "", endDate: "", allDay: false, repeatInfo: null },
  { id: "516", calendar: "Athletics Schedule", calendarColor: "blue", title: "Men's Basketball VS St. Peter's", postedBy: "Anthony Ma", detail: null, location: "Plainfield Gym", start: new Date(2017, 2, 22, 3,15), end: new Date(2017, 2, 22, 3,15), startDate: "", endDate: "", allDay: false, repeatInfo: null },
  { id: "517", calendar: "Athletics Schedule", calendarColor: "black", title: "Women's Fencing VS Newark", postedBy: "Anthony Ma", detail: null, location: "Away", start: new Date(2017, 2, 24), end: new Date(2017, 2, 24, 3,15), startDate: "", endDate: "", allDay: false, repeatInfo: null },
  { id: "518", calendar: "Strata Basic Demo", calendarColor: "pink", title: "Residence Halls close at 8:00 PM", postedBy: "Anthony Ma", detail: "Closed for the duration of Spring Break", location: null, start: new Date(2017, 2, 26, 3,15), end: new Date(2017, 2, 26), startDate: "", endDate: "", allDay: false, repeatInfo: null },
  { id: "519", calendar: "Master Campus", calendarColor: "red", title: "Spring Break begins", postedBy: "Anthony Ma", detail: null, location: null, start: new Date(2017, 2, 27), end: new Date(2017, 2, 27, 3,15), startDate: "", endDate: "", allDay: true, repeatInfo: null },
  { id: "520", calendar: "Strata Basic Demo", calendarColor: "yellow", title: "Spring Mid-Semester Reports sent", postedBy: "Anthony Ma", detail: null, location: null, start: new Date(2017, 2, 31), end: new Date(2017, 2, 31, 3,15), startDate: "", endDate: "", allDay: true, repeatInfo: null },
  { id: "521", calendar: "Strata Basic Demo", calendarColor: "gold", title: "Residence Halls re-open", postedBy: "Anthony Ma", detail: "Halls open at 8:00 AM to take in students returning from Spring Break. ", location: null, start: new Date(2017, 3, 2, 3,15), end: new Date(2017, 3, 2, 3,15), startDate: "", endDate: "", allDay: false, repeatInfo: null },
  { id: "522", calendar: "Strata Basic Demo", calendarColor: "blue", title: "Return to classes (Spring Break ends)", postedBy: "Anthony Ma", detail: null, location: null, start: new Date(2017, 3, 3, 15, 40), end: new Date(2017, 3, 3, 15, 50), startDate: "", endDate: "", allDay: true, repeatInfo: null },
  { id: "523", calendar: "Master Campus", calendarColor: "brown", title: "Fall 2017 Class Registration begins", postedBy: "Anthony Ma", detail: null, location: null, start: new Date(2017, 3, 4, 3,15), end: new Date(2017, 3, 4, 3,15), startDate: "", endDate: "", allDay: false, repeatInfo: null }

];